classdef CompDefaults
    properties (Constant)
%         Synechoccocus_elongatus_UTEX_2973 = struct(['test','']); % Species specific growth parameters for SE
%         Microcystis_aeruginosa = struct(['test','']); % Species specific growth parameters for MA
%         Yarrowia_lipolytico = struct(['test','']); % Species specific growth parameters for YL
%         Custom_Species = struct(['test','']); % Species specific growth parameters for any given custom Species

        defaultFuncVals = struct( ...
            'spec', struct('Multiplicative', struct( ...
                                'Monod', "C1/(C1+K1_1)", ...
                                'Linear', "A*C1", ...
                                'Custoom', "1" ...
                            ), ...
                            'Additive', struct( ...
                                'Monod', "C1/(C1+K1_1)", ...
                                'Linear', "A*C1", ...
                                'Custoom', "1" ...
                            ) ...
                        ), ...
            'chem', struct('Multiplicative', struct( ...
                                'Monod', "C1/(C1+K1_1)", ...
                                'Linear', "A*C1", ...
                                'Custoom', "1" ...
                            ), ...
                            'Additive', struct( ...
                                'Monod', "C1/(C1+K1_1)", ...
                                'Linear', "A*C1", ...
                                'Custoom', "1" ...
                            ) ...
                        ) ...
        );

        validFuncTypes = struct( ...
            'spec', struct('Multiplicative', { ...
                            'Monod', 'Linear', 'Custom' ...
                        }, ...
                        'Additive', { ...
                            'Monod', 'Linear', 'Custom'}), ...
            'chem', struct('Multiplicative', { ...
                            'Monod', 'Linear', 'Custom' ...
                        }, ...
                        'Additive', { ...
                            'Linear', 'Monod', 'Custom'}) ...
        );
    end

    % Format for field - paramVal:
    % replace '^', ' ' with '_'
    % replace '+' with 'p'
    % replace '-' with 'n'
    % replace 'Half-Saturation' with 'K', g/L
    % replace 'Yield' with 'Y', g/g
    % replace 'Death Constant' with 'k', 1/hr
    % replace 'Inhibition Constant' with 'KI', g/L

    methods (Static)
        function specD = CompDefaults()
%             specD.Synechoccocus_elongatus_UTEX_2973.K_NO3_n = 0.032;
        end

        function defaultFuncValue = getDefaultFuncVals(comp, funcCombo, funcType)
            defaultFuncValue = CompDefaults.defaultFuncVals.(comp.getType()).(funcCombo).(funcType);
        end

        function validFuncs = getValidFuncs(comp, funcCombo)
            validFuncs = {CompDefaults.validFuncTypes.(comp.getType()).(funcCombo)};
        end
    end
end