classdef EnvDefaults < handle
    properties (Constant)
        Values = struct(...
            'modelTime',{100}, ...
            'lightFunc',{100}, ...
            'tempFunc',{30}, ...
            'pressFunc',{1.01325}, ...
            'culVol',{(100.*100.*5)./(1E3).*0.99}, ...
            'pH',{7}, ...
            'PBRHt',{100}, ...
            'PBRWidth',{100}, ...
            'PBRDepth',{5}, ...
            'maxVol',{(100.*100.*5)./(1E3)}, ...
            'lgtAttnModel',{'Model 1'}, ...
            'lgtBioAttn',false, ...
            'lgtChemAttn',false ...
        ); % struct containing default parameters for PBR Environment

        Names = [...
            "Photo_Bioreactor_PBR", ...
            "Eutrophic_Lake", ...
            "Test_Tube", ...
            "Shaking_Flask", ...
            "Outdoor_Tank" ...
        ];

        Units = struct( ...
            'modelTime',{'hr'}, ...
            'lightFunc',{'ppf'}, ...
            'tempFunc',{'C'}, ...
            'pressFunc',{'bar'}, ...
            'culVol',{'L'}, ...
            'pH',{'-'}, ...
            'PBRHt',{'cm'}, ...
            'PBRWidth',{'cm'}, ...
            'PBRDepth',{'cm'}, ...
            'maxVol',{'L'}, ...
            'lgtAttnModel',{'-'}, ...
            'lgtBioAttn',{'-'}, ...
            'lgtChemAttn',{'-'} ...
        );
    end

    % Field Naming System:
    % Will match parameter names in Environment class
    % replace ' ', with '_'
    % replace '(', ')' with ''
    % replace '-', with '_'

    methods
        function envD = EnvDefaults()

        end
    end
end