classdef EnvDefaults < handle
    properties (Constant)
        Photo_Bioreactor_PBR = struct(...
            'modelTime',{'20'}, ...
            'lightFunc',{'200'}, ...
            'tempFunc',{'30'}, ...
            'culVol',{'100'}, ...
            'culSA',{'30'} ...
        ); % struct containing default parameters for PBR Environment
        Eutrophic_Lake = struct(...
            'modelTime',{'100'}, ...
            'lightFunc',{'100'}, ...
            'tempFunc',{'30'}, ...
            'culVol',{'100'}, ...
            'culSA',{'30'} ...
        ); % struct containing default parameters for Eutrophic Lake Environment
        Test_Tube = struct(...
            'modelTime',{'100'}, ...
            'lightFunc',{'100'}, ...
            'tempFunc',{'30'}, ...
            'culVol',{'100'}, ...
            'culSA',{'30'} ...
        ); % struct containing default parameters for Test Tube Environment
        Shaking_Flask = struct(...
            'modelTime',{'100'}, ...
            'lightFunc',{'100'}, ...
            'tempFunc',{'30'}, ...
            'culVol',{'100'}, ...
            'culSA',{'30'} ...
        ); % struct containing default parameters for Shaking Flask Environment
        Outdoor_Tank = struct(...
            'modelTime',{'100'}, ...
            'lightFunc',{'100'}, ...
            'tempFunc',{'30'}, ...
            'culVol',{'100'}, ...
            'culSA',{'30'} ...
        ); % struct containing default parameters for Outdoor Tank Environment
        Custom_Env = struct(...
            'modelTime',{'100'}, ...
            'lightFunc',{'100'}, ...
            'tempFunc',{'30'}, ...
            'culVol',{'100'}, ...
            'culSA',{'30'} ...
        ); % struct containing default parameters for Custom Environment

        Units = struct(...
            'modelTime',{'hr'}, ...
            'lightFunc',{'ppf'}, ...
            'tempFunc',{'C'}, ...
            'culVol',{'L'}, ...
            'culSA',{'m^2'} ...
        ); % struct containing default units for each parameter

        Names = [...
            "Photo_Bioreactor_PBR", ...
            "Eutrophic_Lake", ...
            "Test_Tube", ...
            "Shaking_Flask", ...
            "Outdoor_Tank" ...
            ];
    end

    % Field Naming System:
    % Will match parameter names in Environment class
    % replace ' ', with '_'
    % replace '(', ')' with ''
    % replace '-', with '_'

    % Parameter Units:
    % lightFunc: ppf, number | function_handle
    % tempFunc: C, number | function_handle

    methods
        function envD = EnvDefaults()
%             envD.Photo_Bioreactor__PBR_.lightFunc = 100;
%             envD.Photo_Bioreactor__PBR_.tempFunc = 30;
%             envD.Photo_Bioreactor__PBR_.culVol = 100;
%             envD.Photo_Bioreactor__PBR_.culSA = 30;
%             envD.Photo_Bioreactor__PBR_.modelTime = 100;

%             envD.Custom_Env.lightFunc = 100;
%             envD.Custom_Env.tempFunc = 30;
%             envD.Custom_Env.culVol = 100;
%             envD.Custom_Env.culSA = 30;
%             envD.Custom_Env.modelTime = 100;
% 
%             envD.Units.lightFunc = "ppf";
%             envD.Units.tempFunc = "C";
%             envD.Units.culVol = "L";
%             envD.Units.culSA = "m^2";
%             envD.Units.modelTime = "hrs";
        end
    end
end