classdef EnvDefaults < handle
    properties (Constant)
        % ### STARTHERE: add pH in defaults
        Values = struct(...
            'modelTime',{'100'}, ...
            'lightFunc',{'100'}, ...
            'tempFunc',{'30'}, ...
            'pressFunc',{'1.01325'}, ...
            'culVol',{char(string((3.*pi.*(1./2).^2).*1000))}, ...
            'pH',{'7'}, ...
            'agSpd',{'500'}, ...
            'tkHt',{'3'}, ...
            'tkDiam',{'1'}, ...
            'maxVol',{char(string((3.*pi.*(1./2).^2).*1000))}, ...
            'tkSA',{char(string((3.*2.*pi.*(1./2) + pi.*(1./2).^2)))}, ...
            'lgtConfig',{'Internal'}, ...
            'numLgtSrc',{'0'}, ...
            'lgtSrcDiam',{'0'}, ...
            'lgtSrcRad',{'0'} ...
        ); % struct containing default parameters for PBR Environment

        Names = [...
            "Photo_Bioreactor_PBR", ...
            "Eutrophic_Lake", ...
            "Test_Tube", ...
            "Shaking_Flask", ...
            "Outdoor_Tank" ...
        ];

        Units = struct( ...
            'modelTime',{'hr'}, ...
            'lightFunc',{'ppf'}, ...
            'tempFunc',{'C'}, ...
            'pressFunc',{'kPa'}, ...
            'culVol',{'L'}, ...
            'pH',{'-'}, ...
            'agSpd',{'rpm'}, ...
            'tkHt',{'m'}, ...
            'tkDiam',{'m'}, ...
            'maxVol',{'L'}, ...
            'tkSA',{'m^2'}, ...
            'lgtConfig',{'-'}, ...
            'numLgtSrc',{'-'}, ...
            'lgtSrcDiam',{'m'}, ...
            'lgtSrcRad',{'m'} ...
        );
    end

    % Field Naming System:
    % Will match parameter names in Environment class
    % replace ' ', with '_'
    % replace '(', ')' with ''
    % replace '-', with '_'

    methods
        function envD = EnvDefaults()

        end
    end
end